baseURL = "https://mitmproxy.org/"
languageCode = "en-us"
title = "mitmproxy.org"
theme = "mitmproxy"
publishDir = "../public"
relativeURLs = true

[params]
  version = "5.3.0"

[indexes]
  tag = "tags"
